env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2016
  sourceType: module
plugins:
  - prettier
  - react
  - react-hooks
  - '@typescript-eslint'
rules:
  prettier/prettier:
    - error
  react/prop-types: off
  '@typescript-eslint/no-empty-function': off
  '@typescript-eslint/ban-types': off
  '@typescript-eslint/no-explicit-any': off
  'react/display-name': 0
settings:
  react:
    version: detect
